stages:
  - commit-test
  - compliance
  - commit-release-check
  - release-package

include:
  - component: gitlab.com/kipu-all/commons/pipeline-components/compile-typescript@main
    inputs:
      tags:
        - kubernetes
        - cluster
  - component: gitlab.com/kipu-all/commons/oss-compliance/oss-compliance-check@v1.6.3
    inputs:
      tags:
        - kubernetes
        - cluster
  - component: gitlab.com/kipu-all/commons/pipeline-components/semantic-release@main
    inputs:
      tags:
        - kubernetes
        - cluster
  - component: gitlab.com/kipu-all/commons/pipeline-components/publish-npm@main
    inputs:
      tags:
        - kubernetes
        - cluster
